// Package render produces every file the ctl writes for a tenant or the
// fleet: tenant.env, bin/up.sh + bin/down.sh (byte-for-byte ports of
// apptainer/new-tenant.sh's render_* functions — parity_test.go runs the
// script as the oracle), the per-tenant systemd --user units, and the two
// generated nginx includes. Everything is text/template with a strict
// quoting/refusal pass so no operator-supplied value can inject config.
package render

import (
	"bytes"
	"errors"
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"github.com/ragstack/ragstack/internal/ctl/paths"
	"github.com/ragstack/ragstack/internal/ctl/registry"
)

// Placeholders new-tenant.sh prints in --dry-run (stable, leak-free output).
const (
	PlaceholderKeyUser    = "<GENERATED:API_KEY_USER>"
	PlaceholderKeyAdmin   = "<GENERATED:API_KEY_ADMIN>"
	PlaceholderPGPassword = "<GENERATED:PG_PASSWORD>"
)

// Store kinds for the ACL/registry/job stores.
const (
	StoreSQLite   = "sqlite"
	StorePostgres = "postgres"
)

// Secrets are the three per-tenant generated secrets. Zero value + DryRun
// renders placeholders.
type Secrets struct {
	KeyUser, KeyAdmin, PGPassword string
}

// EnvOptions parameterise TenantEnv.
type EnvOptions struct {
	DryRun    bool    // render <GENERATED:*> placeholders instead of Secrets
	Secrets   Secrets // real values (ignored when DryRun)
	StoreKind string  // sqlite (default) | postgres
	PGHost    string  // postgres only
	PGPort    string  // postgres only ("5432" when unset)
	Generator string  // the "(generated by …)" attribution; default "ragstack-ctl"
}

// ScriptGenerator is new-tenant.sh's attribution; the parity test normalises
// the generator line to compare byte-for-byte.
const ScriptGenerator = "apptainer/new-tenant.sh"

// heapPattern is the JVM -Xmx grammar subset new-tenant.sh accepts in practice.
var heapPattern = regexp.MustCompile(`^[1-9][0-9]*[kmgKMG]$`)

// A DSN host/port is interpolated into an unquoted env value and a URL.
var (
	pgHostPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9.-]{0,252}$`)
	pgPortPattern = regexp.MustCompile(`^[1-9][0-9]{0,4}$`)
)

func (o EnvOptions) secrets() Secrets {
	if o.DryRun {
		return Secrets{PlaceholderKeyUser, PlaceholderKeyAdmin, PlaceholderPGPassword}
	}
	return o.Secrets
}

// envData is what the tenant.env template sees.
type envData struct {
	Name, TDir, EnvFile, Generator string
	Ports                          registry.Ports
	Postgres                       bool
	PGHost, PGPort                 string
	KeyUser, KeyAdmin, PGPassword  string
}

var envTmpl = template.Must(template.New("tenant.env").Parse(`# ==========================================================================
# tenant.env — tenant '{{.Name}}' (generated by {{.Generator}})
#
# Load with:   set -a; . {{.EnvFile}}; set +a
# Never pipe through xargs — it strips the quotes around JSON values.
# JSON values MUST stay single-quoted (this file is shell-sourced).
# Re-running new-tenant.sh KEEPS an edited copy of this file (use --force
# to overwrite); it never re-generates the API keys or the DB password.
# ==========================================================================

# --- identity / authz -----------------------------------------------------
API_KEYS='["{{.KeyUser}}","{{.KeyAdmin}}"]'
API_KEY_TENANTS='{"{{.KeyUser}}":"{{.Name}}","{{.KeyAdmin}}":"{{.Name}}"}'
API_KEY_ROLES='{"{{.KeyUser}}":"user","{{.KeyAdmin}}":"admin"}'
DEFAULT_ROLE=user
IDENTITY_PROVIDER=none
# To accept bearer identities instead, pick one and fill in the pins:
# IDENTITY_PROVIDER=oidc
# IDENTITY_OIDC_ISSUER=https://accounts.example.com
# IDENTITY_OIDC_CLIENT_IDS='["<client-id>"]'
# IDENTITY_PROVIDER=bvbrc    # issuer allowlist is pinned in config.py
MAX_COLLECTIONS=100
{{if .Postgres -}}
USER_STORE_BACKEND=postgres
USER_STORE_DSN=postgresql://{{.Name}}:{{.PGPassword}}@{{.PGHost}}:{{.PGPort}}/{{.Name}}
{{else -}}
USER_STORE_BACKEND=sqlite
USER_STORE_PATH={{.TDir}}/state/ragstack_users.db
{{end -}}
ACL_BACKFILL_OWNER=legacy:admin

# --- dedicated stores (ADR-0005: data at rest defines the tenant) ---------
VECTOR_BACKEND=qdrant
QDRANT_URL=http://localhost:{{.Ports.QdrantHTTP}}
TEXT_BACKEND=elasticsearch
ELASTICSEARCH_URL=http://localhost:{{.Ports.ESHTTP}}
GRAPH_BACKEND=disabled
{{if .Postgres -}}
JOB_STORE_BACKEND=postgres
POSTGRES_DSN=postgresql+asyncpg://{{.Name}}:{{.PGPassword}}@{{.PGHost}}:{{.PGPort}}/{{.Name}}
COLLECTION_STORE_BACKEND=postgres
COLLECTION_STORE_DSN=postgresql://{{.Name}}:{{.PGPassword}}@{{.PGHost}}:{{.PGPort}}/{{.Name}}
{{else -}}
JOB_STORE_BACKEND=sqlite
JOB_STORE_PATH={{.TDir}}/state/ragstack_jobs.db
COLLECTION_STORE_BACKEND=sqlite
COLLECTION_STORE_PATH={{.TDir}}/state/ragstack_collections.db
{{end -}}
COLLECTION_MANIFEST_DIR={{.TDir}}/manifests
# COLLECTIONS_FILE={{.TDir}}/config/collections.json   # optional one-time registry seed

# --- embedding / rerank (shared stateless compute, per ADR-0005) ----------
EMBEDDING_API=openai
EMBEDDING_ENDPOINTS='["http://localhost:9001","http://localhost:9002"]'
EMBEDDING_MODEL=Salesforce/SFR-Embedding-Mistral
EMBEDDING_MODEL_DIM=4096
EMBEDDING_SIDECAR_URL=http://localhost:50053
CROSSENCODER_SIDECAR_URL=http://localhost:50052

# --- safety ----------------------------------------------------------------
REQUIRE_DURABLE_BACKENDS=true
INGEST_ROOT={{.TDir}}/ingest
MAX_DOCUMENT_BYTES=50000000

# --- API -------------------------------------------------------------------
# PORT is informational only — the API's Settings does not read it; uvicorn
# needs --port {{.Ports.API}} explicitly (see the start command below/in the plan).
PORT={{.Ports.API}}
LOG_LEVEL=INFO
`))

// TenantEnv renders tenant.env for t exactly as apptainer/new-tenant.sh's
// render_env does (sqlite and postgres branches), attribution aside.
func TenantEnv(t *registry.Tenant, o EnvOptions) ([]byte, error) {
	if err := checkTenant(t, scriptCheck); err != nil {
		return nil, err
	}
	kind := o.StoreKind
	if kind == "" {
		kind = StoreSQLite
	}
	if kind != StoreSQLite && kind != StorePostgres {
		return nil, fmt.Errorf("unknown store kind %q", kind)
	}
	gen := o.Generator
	if gen == "" {
		gen = "ragstack-ctl"
	}
	s := o.secrets()
	d := envData{
		Name: t.Name, TDir: t.DataDir, EnvFile: filepath.Join(t.DataDir, "config", "tenant.env"), Generator: gen,
		Ports: t.Ports, Postgres: kind == StorePostgres, PGHost: o.PGHost, PGPort: o.PGPort,
		KeyUser: s.KeyUser, KeyAdmin: s.KeyAdmin, PGPassword: s.PGPassword,
	}
	if d.Postgres {
		if d.PGHost == "" {
			return nil, errors.New("postgres store kind requires PGHost")
		}
		if d.PGPort == "" {
			d.PGPort = "5432"
		}
		if !pgHostPattern.MatchString(d.PGHost) || !pgPortPattern.MatchString(d.PGPort) {
			return nil, fmt.Errorf("unsafe postgres host/port %q:%q (host [A-Za-z0-9.-], port digits)", d.PGHost, d.PGPort)
		}
	}
	for _, v := range []string{s.KeyUser, s.KeyAdmin, s.PGPassword} {
		if strings.ContainsAny(v, "'\"\n\\") {
			return nil, errors.New("secret value contains a quote, backslash or newline and cannot be rendered")
		}
	}
	return execTmpl(envTmpl, d)
}

// StoreOptions parameterise UpSh.
type StoreOptions struct {
	Images string // RAG_IMAGES (shared SIF dir)
	ESHeap string // ES_JAVA_OPTS -Xms/-Xmx; default 512m
}

type upData struct {
	Name, IMG, TDir, ESHeap string
	Ports                   registry.Ports
}

// upTmpl is render_up_sh verbatim. Backticks in the script's here-doc do not
// occur; `$` sequences are literal here because text/template does not
// expand them.
var upTmpl = template.Must(template.New("up.sh").Parse(`#!/usr/bin/env bash
# Start the dedicated stores for tenant '{{.Name}}'.
# Generated by apptainer/new-tenant.sh — do not edit; re-run it to regenerate.
#
# Instances: qdrant-{{.Name}} (http :{{.Ports.QdrantHTTP}}, grpc :{{.Ports.QdrantGRPC}})
#            elasticsearch-{{.Name}} (http :{{.Ports.ESHTTP}}, transport :{{.Ports.ESTransport}})
set -euo pipefail
IMG="{{.IMG}}"
TDIR="{{.TDir}}"

require_sif() {
    [[ -f "$1" ]] || { echo "ERROR: missing $1 — run apptainer/pull.sh"; exit 1; }
}

already_running() {
    apptainer instance list 2>/dev/null | awk 'NR>1 {print $1}' | grep -qx "$1"
}

# Seed an empty host bind dir from the image's copy of the same path.
seed_if_empty() {
    local sif="$1" container_path="$2" host_path="$3"
    if [[ -n "$(ls -A "$host_path" 2>/dev/null)" ]]; then return; fi
    echo "  seeding $host_path from $sif:$container_path"
    apptainer exec --bind "$host_path:/__seed" "$sif" \
        sh -c "cp -R $container_path/. /__seed/"
}

start() {
    local name="$1" sif="$2"; shift 2
    require_sif "$sif"
    if already_running "$name"; then
        echo "[$name] already running — skipping"
        return
    fi
    # Split remaining args at ` + "`--`" + `: before are apptainer options,
    # after are runscript args (passed to the container CMD).
    local opts=() args=() mode=opts
    for a in "$@"; do
        if [[ "$a" == "--" ]]; then mode=args; continue; fi
        if [[ "$mode" == opts ]]; then opts+=("$a"); else args+=("$a"); fi
    done
    echo "[$name] starting"
    apptainer instance run "${opts[@]}" "$sif" "$name" "${args[@]}"
}

mmc=$(sysctl -n vm.max_map_count 2>/dev/null || echo 0)
if (( mmc < 262144 )); then
    echo "WARN: vm.max_map_count=$mmc (<262144) — Elasticsearch will fail to start."
    echo "      Fix once with: sudo sysctl -w vm.max_map_count=262144"
fi

# Apptainer has no --cwd flag and qdrant's CMD is CWD-relative — cd first.
# Ports via double-underscore envs (safe: no dots for the shell to mangle).
start qdrant-{{.Name}} "$IMG/qdrant.sif" \
    --bind "$TDIR/qdrant/storage:/qdrant/storage" \
    --bind "$TDIR/qdrant/snapshots:/qdrant/snapshots" \
    --env QDRANT__SERVICE__HTTP_PORT={{.Ports.QdrantHTTP}} \
    --env QDRANT__SERVICE__GRPC_PORT={{.Ports.QdrantGRPC}} \
    -- /bin/sh -c 'cd /qdrant && exec ./entrypoint.sh'

# ES config must carry the image's files before first start (an empty bind
# breaks startup).
seed_if_empty "$IMG/elasticsearch.sif" /usr/share/elasticsearch/config \
    "$TDIR/elasticsearch/config"

# Dotted ES settings CANNOT go through --env (apptainer shell-sources it) —
# use native -E args, and call docker-entrypoint.sh directly: /bin/tini
# greedily parses -E as its own option.
start elasticsearch-{{.Name}} "$IMG/elasticsearch.sif" \
    --bind "$TDIR/elasticsearch/data:/usr/share/elasticsearch/data" \
    --bind "$TDIR/elasticsearch/logs:/usr/share/elasticsearch/logs" \
    --bind "$TDIR/elasticsearch/config:/usr/share/elasticsearch/config" \
    --env ES_JAVA_OPTS="-Xms{{.ESHeap}} -Xmx{{.ESHeap}}" \
    -- /usr/local/bin/docker-entrypoint.sh eswrapper \
        -Ediscovery.type=single-node \
        -Expack.security.enabled=false \
        -Ehttp.port={{.Ports.ESHTTP}} \
        -Etransport.port={{.Ports.ESTransport}}

echo
apptainer instance list
`))

var downTmpl = template.Must(template.New("down.sh").Parse(`#!/usr/bin/env bash
# Stop the dedicated stores for tenant '{{.Name}}'. Idempotent.
# Generated by apptainer/new-tenant.sh — do not edit; re-run it to regenerate.
set -euo pipefail
for name in qdrant-{{.Name}} elasticsearch-{{.Name}}; do
    if apptainer instance stop "$name" 2>/dev/null; then
        echo "[$name] stopped"
    else
        echo "[$name] not running"
    fi
done
`))

// UpSh renders bin/up.sh (render_up_sh).
func UpSh(t *registry.Tenant, o StoreOptions) ([]byte, error) {
	if err := checkTenant(t, scriptCheck); err != nil {
		return nil, err
	}
	if o.Images == "" {
		return nil, errors.New("Images (RAG_IMAGES) is required")
	}
	heap := o.ESHeap
	if heap == "" {
		heap = "512m"
	}
	if !heapPattern.MatchString(heap) {
		return nil, fmt.Errorf("invalid ES heap %q (want e.g. 512m, 2g)", heap)
	}
	if strings.ContainsAny(o.Images, "\"$`\\\n") {
		return nil, fmt.Errorf("unsafe images path %q", o.Images)
	}
	return execTmpl(upTmpl, upData{Name: t.Name, IMG: o.Images, TDir: t.DataDir, ESHeap: heap, Ports: t.Ports})
}

// DownSh renders bin/down.sh (render_down_sh).
func DownSh(t *registry.Tenant) ([]byte, error) {
	if err := checkTenant(t, scriptCheck); err != nil {
		return nil, err
	}
	return execTmpl(downTmpl, upData{Name: t.Name})
}

// checkOptions are the refusals a caller may waive.
type checkOptions struct {
	// AllowOffLayoutDataDir waives the data_dir/manifest_name agreement
	// check below.
	AllowOffLayoutDataDir bool
}

// scriptCheck is what the three script renderers pass. They interpolate
// t.DataDir VERBATIM and derive no sibling path from it, so their output is
// correct for a data dir of any name; only Units, which derives the whole
// unit's paths from the data dir while naming instances and log files after
// manifest_name, needs the two to agree.
var scriptCheck = checkOptions{AllowOffLayoutDataDir: true}

func checkTenant(t *registry.Tenant, opts checkOptions) error {
	if t == nil {
		return errors.New("nil tenant")
	}
	if err := paths.ValidateName(t.Name); err != nil {
		return err
	}
	// The manifest name is a path segment too — it names the data dir, the
	// log files, the apptainer instances and the manifest.tsv row — so it is
	// exactly as load-bearing as the tenant name and was the only one of the
	// two nothing validated.
	if t.ManifestName != "" && t.ManifestName != t.Name {
		if err := paths.ValidateName(t.ManifestName); err != nil {
			return fmt.Errorf("manifest_name: %w", err)
		}
	}
	if t.DataDir != "" {
		if _, err := paths.SafePath("/", t.DataDir); err != nil {
			return fmt.Errorf("data_dir: %w", err)
		}
		// The data dir's basename IS the manifest name in the host layout,
		// and a renderer that derives sibling paths from the data dir while
		// naming instances and logs after manifest_name needs that to hold:
		// otherwise the unit binds one tenant's store directory and writes
		// the other tenant's log. adopt records the disagreement as
		// data_dir_off_layout, so it is a known, nameable state — refused
		// here rather than silently rendered into a systemd file.
		if base := filepath.Base(t.DataDir); !opts.AllowOffLayoutDataDir && t.ManifestName != "" && base != t.ManifestName {
			return fmt.Errorf("tenant %s: data_dir %s is named %q but manifest_name is %q — the rendered paths would describe two different tenants (set AllowOffLayoutDataDir to render it anyway)", t.Name, t.DataDir, base, t.ManifestName)
		}
	}
	if t.Ports.Base == 0 {
		return errors.New("tenant has no port block")
	}
	return nil
}

func execTmpl(tmpl *template.Template, data any) ([]byte, error) {
	var b bytes.Buffer
	if err := tmpl.Execute(&b, data); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// sortedTenants returns the fleet's tenants in display_order, then any
// remaining ones sorted by name.
func sortedTenants(f *registry.Fleet) []*registry.Tenant {
	var out []*registry.Tenant
	seen := map[string]bool{}
	for _, n := range f.DisplayOrder {
		if t, ok := f.Tenants[n]; ok && !seen[n] {
			out = append(out, t)
			seen[n] = true
		}
	}
	var rest []string
	for n := range f.Tenants {
		if !seen[n] {
			rest = append(rest, n)
		}
	}
	sort.Strings(rest)
	for _, n := range rest {
		out = append(out, f.Tenants[n])
	}
	return out
}
