"""One mutable request context in one contextvar, plus the logging filter that
copies it onto every ``LogRecord``.

**Why ONE mutable object rather than one contextvar per field.** ``tenant`` and
``role`` are only *known* after ``security.resolve_principal`` has run — deep
inside the app, below the middleware, and frequently inside a task spawned by
``asyncio.gather``. ``ContextVar.set()`` in a child context does **not**
propagate back to the parent, so a middleware that has to render a summary line
in its ``finally`` would never see a value set down there. In-place mutation of
a shared object **does** propagate, because every child context holds the same
object reference.

So the contract is exactly one sentence, and the whole package depends on it:

    The middleware calls :func:`set_context` **once** per request. Everything
    below it **mutates the object in place** and never calls ``set()``.

Five mechanics an implementer will otherwise get wrong:

1. ``ContextVar.set()`` below the middleware is invisible to the middleware.
   Mutate; do not set. (Probed both ways.)
2. ``asyncio.gather`` children copy the context, so they see the *same object*
   and their mutations are visible to the parent. This is what makes per-leg
   attribution possible at all.
3. The middleware must install a **fresh** object per request. A module-scope
   default, or reuse, leaks request N's data onto request N+1 and every number
   is then quietly wrong.
4. A ``create_task`` started during a request and never awaited keeps the
   context and can mutate an object that has already been logged. Harmless (the
   object is garbage by then) but its work is **missing** from the line.
5. ``asyncio.to_thread`` and ``anyio.to_thread.run_sync`` — FastAPI's
   sync-endpoint path — **do** propagate the context, so context read from sync
   code works. A raw ``loop.run_in_executor(ThreadPoolExecutor(), …)`` does
   **not**: the var reads as unset and anything context-dependent silently
   no-ops. There are currently **zero** such calls in ``ragstack``; this is
   latent, not live, and it is written down so it stays that way.

The context deliberately carries **no credential material**. ``token`` and
``api_key`` never belong here — see the package docstring.
"""

from __future__ import annotations

import logging
from contextvars import ContextVar, Token
from dataclasses import dataclass, field

#: Rendered in place of any field that was never populated. A literal ``-`` (not
#: an empty string) so a logfmt line stays parseable and a human scanning a
#: column sees "not known" rather than a gap.
MISSING = "-"

#: The record attributes this module writes. Kept in one place because the
#: formatters in ``logging_config`` iterate it, and because a record that never
#: passed through the filter (uvicorn's, ``warnings``') must still format — the
#: filter fills every one of these on every record it sees.
CONTEXT_FIELDS = ("rid", "upstream_rid", "tenant", "role", "route")


@dataclass
class RequestContext:
    """Per-request correlation data. Mutated in place; never re-``set()``.

    ``stages`` is a placeholder slot for W3's timing accumulator so that the
    object shape does not change under producers when it lands. W1 neither
    writes nor reads it.
    """

    #: Always ours, always generated by the middleware. Never caller-supplied.
    request_id: str
    #: A caller-supplied ``X-Request-ID`` that passed validation, recorded for
    #: gateway correlation and **never echoed**. Empty when absent or rejected.
    upstream_request_id: str = ""
    tenant: str = ""
    role: str = ""
    route: str = ""
    #: Registry collection id, populated by the query path in W3.
    collection: str = ""
    #: W3's ``StageTimings``. Untouched in W1.
    stages: object | None = field(default=None, repr=False)


_ctx: ContextVar[RequestContext | None] = ContextVar("ragstack_request_context", default=None)


def current_context() -> RequestContext | None:
    """The context for the request being served, or ``None`` outside one.

    ``None`` is the normal state for CLI scripts, library callers and unit tests
    — every consumer must tolerate it rather than assume a request is in flight.
    """
    return _ctx.get()


def set_context(ctx: RequestContext) -> Token[RequestContext | None]:
    """Install ``ctx`` as the current context. **Middleware only.**

    Returns the reset token, which the middleware deliberately does *not* use:
    an application-level ``Exception`` handler runs after the middleware's
    ``finally`` in the same task context, and resetting would blank the id that
    handler needs to stamp the response header. Per-request isolation comes from
    installing a *fresh* object at entry, not from resetting at exit.
    """
    return _ctx.set(ctx)


class RequestContextFilter(logging.Filter):
    """Copy the current request context onto every ``LogRecord``.

    This is the mechanism that gives the ~219 existing ad-hoc ``log.*`` call
    sites in ``ragstack`` a request id with **zero call-site edits**: the record
    is decorated on its way to the handler, not at the point it is written.

    Installed on the *handler*, not on a logger — a logger-level filter is not
    consulted for records that propagate up from a child logger, which would
    silently skip most of the tree. Fields that were never populated become
    :data:`MISSING`, so a record from uvicorn or from ``warnings`` — which never
    saw a request context — still formats rather than raising ``KeyError`` in
    the formatter.

    Never returns ``False``: a filter used for decoration must not also drop
    records.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        ctx = _ctx.get()
        if ctx is None:
            for name in CONTEXT_FIELDS:
                if not hasattr(record, name):
                    setattr(record, name, MISSING)
            return True
        record.rid = ctx.request_id or MISSING
        record.upstream_rid = ctx.upstream_request_id or MISSING
        record.tenant = ctx.tenant or MISSING
        record.role = ctx.role or MISSING
        record.route = ctx.route or MISSING
        return True
