package grading

// CPython's Mersenne Twister, ported byte-for-byte.
//
// `GradingBatch`'s reader-order rule is NORMATIVE for every implementation:
// the reader at index k sees the batch's tasks in batch order permuted by
//
//	random.Random(order_seed + k + 1).shuffle(list(range(task_count)))
//
// evaluated by CPython. That is the exact expression
// `docs/plans/results/stage0/s0_rdev.py` used to build the
// RDEV-readsheet-A/B.html sheets, so a read begun on those sheets continues in
// the UI at the same position — and it is what makes the Go API and the Python
// API show ONE reader ONE order. A "good enough" shuffle here is not a cosmetic
// difference: it is two servers disagreeing about which pair a reader is on.
//
// Reproducing it means reproducing three things exactly, not approximately:
//
//  1. how CPython SEEDS MT19937 from an int (`init_by_array` over the seed's
//     32-bit little-endian limbs, of its ABSOLUTE value — a negative seed is
//     legal in the schema and CPython takes abs());
//  2. `getrandbits(k)`, which is the top k bits of one 32-bit draw for k <= 32;
//  3. `random.Random._randbelow_with_getrandbits` — rejection sampling on
//     n.bit_length() — and `random.shuffle`'s Fisher-Yates FROM THE END.
//
// Every one of those is pinned against the project interpreter in
// cpyrand_test.go; the fixtures there were generated by
// /rag/envs/ragstack/bin/python3, not by this file.

const (
	mtN         = 624
	mtM         = 397
	mtMatrixA   = 0x9908b0df
	mtUpperMask = 0x80000000
	mtLowerMask = 0x7fffffff
)

// mt19937 is the generator behind CPython's `random.Random`.
type mt19937 struct {
	state [mtN]uint32
	index int
}

// initGenrand is CPython's `init_genrand` (Random_seed's scalar path).
func (m *mt19937) initGenrand(s uint32) {
	m.state[0] = s
	for i := 1; i < mtN; i++ {
		prev := m.state[i-1]
		m.state[i] = 1812433253*(prev^(prev>>30)) + uint32(i)
	}
	m.index = mtN
}

// initByArray is CPython's `init_by_array` — the path an int seed takes.
func (m *mt19937) initByArray(key []uint32) {
	m.initGenrand(19650218)
	i, j := 1, 0
	k := mtN
	if len(key) > k {
		k = len(key)
	}
	for ; k > 0; k-- {
		prev := m.state[i-1]
		m.state[i] = (m.state[i] ^ ((prev ^ (prev >> 30)) * 1664525)) + key[j] + uint32(j)
		i++
		j++
		if i >= mtN {
			m.state[0] = m.state[mtN-1]
			i = 1
		}
		if j >= len(key) {
			j = 0
		}
	}
	for k = mtN - 1; k > 0; k-- {
		prev := m.state[i-1]
		m.state[i] = (m.state[i] ^ ((prev ^ (prev >> 30)) * 1566083941)) - uint32(i)
		i++
		if i >= mtN {
			m.state[0] = m.state[mtN-1]
			i = 1
		}
	}
	// MSB is 1, assuring a non-zero initial array.
	m.state[0] = 0x80000000
}

// genrandUint32 is CPython's `genrand_uint32`: one tempered 32-bit draw.
func (m *mt19937) genrandUint32() uint32 {
	if m.index >= mtN {
		var y uint32
		for kk := 0; kk < mtN-mtM; kk++ {
			y = (m.state[kk] & mtUpperMask) | (m.state[kk+1] & mtLowerMask)
			m.state[kk] = m.state[kk+mtM] ^ (y >> 1) ^ ((y & 1) * mtMatrixA)
		}
		for kk := mtN - mtM; kk < mtN-1; kk++ {
			y = (m.state[kk] & mtUpperMask) | (m.state[kk+1] & mtLowerMask)
			m.state[kk] = m.state[kk+(mtM-mtN)] ^ (y >> 1) ^ ((y & 1) * mtMatrixA)
		}
		y = (m.state[mtN-1] & mtUpperMask) | (m.state[0] & mtLowerMask)
		m.state[mtN-1] = m.state[mtM-1] ^ (y >> 1) ^ ((y & 1) * mtMatrixA)
		m.index = 0
	}
	y := m.state[m.index]
	m.index++
	y ^= y >> 11
	y ^= (y << 7) & 0x9d2c5680
	y ^= (y << 15) & 0xefc60000
	y ^= y >> 18
	return y
}

// pyRandom is `random.Random(seed)` for an INTEGER seed.
type pyRandom struct{ mt mt19937 }

// newPyRandom seeds exactly as CPython's `random_seed` does for a PyLong:
// take the absolute value, split it into 32-bit little-endian limbs (one limb
// of 0 when the value is zero), and hand those to init_by_array.
//
// The absolute value matters: `order_seed` is a plain `integer` in the schema
// with no minimum, so a study is free to seed with a negative number, and
// CPython's `random.Random(-6)` is `random.Random(6)`'s state.
func newPyRandom(seed int64) *pyRandom {
	var mag uint64
	if seed < 0 {
		// -math.MinInt64 overflows int64; negate in the unsigned domain.
		mag = uint64(-(seed + 1)) + 1
	} else {
		mag = uint64(seed)
	}
	key := []uint32{uint32(mag & 0xffffffff)}
	if hi := uint32(mag >> 32); hi != 0 {
		key = append(key, hi)
	}
	r := &pyRandom{}
	r.mt.initByArray(key)
	return r
}

// random is CPython's `random_random`: a 53-bit float built from two 32-bit
// draws (27 high bits then 26). Nothing in the reader order uses it — shuffle
// goes through getrandbits — but it is the cheapest end-to-end assertion that
// the seeding and the tempering match CPython, so cpyrand_test.go pins it.
func (r *pyRandom) random() float64 {
	a := r.mt.genrandUint32() >> 5
	b := r.mt.genrandUint32() >> 6
	return (float64(a)*67108864.0 + float64(b)) * (1.0 / 9007199254740992.0)
}

// getrandbits is CPython's `random_getrandbits` for 0 < k <= 32 — the only
// widths a shuffle of a JSON array can ask for (a batch would need 2^32 tasks
// to need more). Wider draws are not implemented rather than implemented
// wrongly; randBelow's caller guards the width.
func (r *pyRandom) getrandbits(k uint) uint32 {
	if k == 0 {
		return 0
	}
	return r.mt.genrandUint32() >> (32 - k)
}

// randBelow is `random.Random._randbelow_with_getrandbits(n)`: rejection
// sampling on exactly n.bit_length() bits. The rejection loop is what makes the
// draw uniform AND what makes the stream position depend on the rejects, so a
// "take the modulus" shortcut would diverge from CPython on the very first
// unlucky draw, not just in distribution.
func (r *pyRandom) randBelow(n uint32) uint32 {
	if n == 0 {
		return 0
	}
	k := uint(0)
	for v := n; v > 0; v >>= 1 {
		k++
	}
	for {
		v := r.getrandbits(k)
		if v < n {
			return v
		}
	}
}

// shuffle is `random.shuffle(x)` (Python >= 3.2, no `random` argument):
// Fisher-Yates walking DOWN from the last index. Walking up produces a
// different permutation from the same stream, which is the kind of bug that
// only shows up as two readers being handed each other's order.
func (r *pyRandom) shuffle(x []int) {
	for i := len(x) - 1; i > 0; i-- {
		j := int(r.randBelow(uint32(i + 1)))
		x[i], x[j] = x[j], x[i]
	}
}

// MaxOrderTaskCount is the largest task_count ReaderOrder will permute. It is
// the width limit of the getrandbits path above, stated as a number rather than
// left implicit; no batch approaches it (the contract calls a read "a few
// hundred tasks").
const MaxOrderTaskCount = 1 << 31

// ReaderOrder returns the batch's private permutation for one reader, as
// indices into batch order — the contract's normative rule, evaluated here
// exactly as CPython evaluates it:
//
//	random.Random(orderSeed + readerIndex + 1).shuffle(list(range(taskCount)))
func ReaderOrder(orderSeed int64, readerIndex int, taskCount int) []int {
	order := make([]int, taskCount)
	for i := range order {
		order[i] = i
	}
	if taskCount < 2 || taskCount > MaxOrderTaskCount {
		return order
	}
	newPyRandom(orderSeed + int64(readerIndex) + 1).shuffle(order)
	return order
}
