package grading

import (
	"reflect"
	"testing"
)

// The fixtures below were GENERATED BY THE PROJECT INTERPRETER, not written by
// hand and not produced by this package:
//
//	/rag/envs/ragstack/bin/python3 -c 'import random; ...'   (CPython 3.12.13)
//
// That is the whole point. `GradingBatch`'s reader-order rule names CPython's
// `random.Random(...).shuffle` as normative, so the only evidence that this Go
// port implements the rule is agreement with CPython on values CPython
// produced. A test that compared this port against itself would pass on any
// self-consistent generator, including a wrong one.
//
// Regenerate with:
//
//	python3 -c 'import random
//	def o(seed,k,n):
//	    x=list(range(n)); random.Random(seed+k+1).shuffle(x); return x
//	print(o(20260915,0,6))'

// --------------------------------------------------------------------------- //
// The stream itself: random() and getrandbits(32)
// --------------------------------------------------------------------------- //
// Pinning random() pins the seeding (init_by_array over the seed's 32-bit
// little-endian limbs) and the tempering, independently of the shuffle logic
// layered on top — so a failure here says "the generator is wrong" rather than
// "the permutation is wrong", which are different bugs.
func TestRandomMatchesCPython(t *testing.T) {
	cases := []struct {
		seed   int64
		floats []float64
		bits   []uint32
	}{
		{20260916, []float64{0.6624941903573036, 0.6825255929118569, 0.9420456376610188}, []uint32{3737271882, 2764358238}},
		{20260917, []float64{0.6166608268820462, 0.6548790781003029, 0.9775360282732938}, []uint32{3804261718, 1333289222}},
		{6, []float64{0.793340083761663, 0.8219540423197268, 0.4850346279309453}, []uint32{1123655737, 158152503}},
		{5, []float64{0.6229016948897019, 0.7417869892607294, 0.7951935655656966}, []uint32{4047793130, 3614262064}},
		{0, []float64{0.8444218515250481, 0.7579544029403025, 0.420571580830845}, []uint32{1112038970, 4146640122}},
	}
	for _, c := range cases {
		r := newPyRandom(c.seed)
		for i, want := range c.floats {
			if got := r.random(); got != want {
				t.Fatalf("seed %d: random() draw %d = %v, CPython says %v", c.seed, i, got, want)
			}
		}
		for i, want := range c.bits {
			if got := r.getrandbits(32); got != want {
				t.Fatalf("seed %d: getrandbits(32) draw %d = %d, CPython says %d", c.seed, i, got, want)
			}
		}
	}
}

// A negative seed is legal (`order_seed` is a bare `integer` in the schema) and
// CPython seeds from its ABSOLUTE value, so Random(-6) and Random(6) are the
// same generator. Asserted directly, because "take abs()" is the single line
// most likely to be dropped by a reader porting init_by_array.
func TestNegativeSeedUsesAbsoluteValueLikeCPython(t *testing.T) {
	neg, pos := newPyRandom(-6), newPyRandom(6)
	for i := 0; i < 4; i++ {
		if a, b := neg.random(), pos.random(); a != b {
			t.Fatalf("draw %d: Random(-6)=%v but Random(6)=%v; CPython makes them equal", i, a, b)
		}
	}
}

// --------------------------------------------------------------------------- //
// The contract's rule: random.Random(order_seed + k + 1).shuffle(range(n))
// --------------------------------------------------------------------------- //
func TestReaderOrderMatchesCPython(t *testing.T) {
	cases := []struct {
		seed  int64
		index int
		want  []int
	}{
		// The study's SEED_RDEV, reader A (+1) and reader B (+2) — the two
		// permutations RDEV-readsheet-A/B.html were built with.
		{20260915, 0, []int{1, 2, 4, 3, 0, 5}},
		{20260915, 0, []int{1, 4, 3, 7, 9, 5, 8, 2, 6, 0}},
		{20260915, 0, []int{50, 32, 94, 35, 57, 10, 65, 86, 9, 46, 2, 72, 29, 27, 33, 14, 45, 18, 81, 11, 92, 0, 25, 70, 15, 83, 96, 40, 42, 41, 24, 21, 59, 6, 88, 8, 79, 17, 93, 36, 49, 43, 39, 7, 44, 19, 37, 76, 28, 74, 97, 26, 89, 90, 95, 54, 63, 66, 3, 4, 85, 1, 12, 61, 38, 60, 23, 98, 62, 16, 51, 67, 53, 52, 58, 69, 34, 55, 22, 80, 31, 68, 78, 71, 91, 77, 73, 99, 56, 75, 30, 64, 47, 13, 82, 20, 48, 87, 5, 84}},
		{20260915, 1, []int{3, 0, 5, 2, 1, 4}},
		{20260915, 1, []int{6, 5, 3, 0, 1, 7, 8, 4, 2, 9}},
		{20260915, 1, []int{75, 53, 94, 4, 90, 38, 22, 10, 21, 11, 99, 7, 56, 9, 52, 57, 14, 86, 23, 95, 48, 82, 98, 81, 87, 59, 77, 80, 62, 85, 55, 51, 88, 40, 8, 92, 64, 60, 41, 45, 43, 35, 1, 17, 72, 49, 58, 31, 36, 6, 46, 76, 34, 68, 13, 74, 65, 24, 79, 12, 54, 29, 84, 25, 28, 32, 44, 20, 67, 93, 91, 63, 3, 37, 15, 73, 19, 5, 89, 2, 50, 61, 27, 97, 26, 66, 69, 42, 70, 47, 18, 0, 30, 71, 33, 39, 96, 83, 16, 78}},
		// The seed conformance/test_grading.py uses.
		{4242, 0, []int{2, 1, 5, 0, 3, 4}},
		{4242, 0, []int{5, 1, 4, 6, 3, 2, 9, 0, 7, 8}},
		{4242, 0, []int{44, 73, 36, 30, 62, 3, 93, 67, 80, 31, 22, 7, 10, 95, 23, 46, 58, 4, 78, 74, 61, 69, 57, 8, 65, 13, 0, 45, 48, 9, 27, 71, 90, 86, 34, 83, 19, 98, 96, 41, 75, 64, 76, 55, 70, 85, 33, 89, 26, 88, 81, 72, 21, 32, 38, 79, 17, 35, 18, 24, 99, 68, 15, 53, 91, 49, 92, 39, 59, 60, 2, 28, 77, 94, 6, 20, 50, 14, 54, 37, 16, 51, 52, 84, 43, 87, 5, 29, 11, 42, 40, 82, 25, 12, 63, 47, 97, 1, 56, 66}},
		{4242, 1, []int{4, 5, 0, 2, 3, 1}},
		{4242, 1, []int{0, 8, 6, 2, 9, 5, 1, 4, 7, 3}},
		{4242, 1, []int{6, 86, 1, 59, 22, 79, 14, 83, 43, 78, 3, 0, 75, 39, 57, 54, 85, 32, 31, 93, 13, 7, 94, 87, 26, 72, 2, 47, 82, 61, 36, 97, 51, 76, 20, 29, 68, 95, 30, 58, 99, 49, 96, 74, 11, 18, 90, 70, 19, 65, 10, 66, 64, 24, 89, 15, 91, 48, 45, 67, 53, 38, 37, 17, 69, 8, 34, 88, 84, 16, 4, 41, 21, 62, 5, 73, 33, 23, 25, 9, 44, 92, 46, 71, 12, 80, 77, 56, 52, 55, 98, 63, 42, 40, 50, 81, 27, 35, 60, 28}},
		// seed 0 — the limb-count edge (CPython feeds init_by_array a single
		// zero limb rather than an empty key).
		{0, 0, []int{2, 3, 5, 0, 4, 1}},
		{0, 0, []int{6, 8, 9, 7, 5, 3, 0, 4, 1, 2}},
		{0, 1, []int{2, 3, 1, 4, 5, 0}},
		{0, 1, []int{5, 9, 3, 4, 6, 7, 2, 8, 1, 0}},
		// A negative seed: -7 + 0 + 1 = -6 and -7 + 1 + 1 = -5.
		{-7, 0, []int{2, 5, 1, 3, 0, 4}},
		{-7, 0, []int{5, 8, 3, 4, 0, 2, 6, 7, 1, 9}},
		{-7, 1, []int{1, 0, 3, 5, 2, 4}},
		{-7, 1, []int{2, 3, 1, 0, 8, 7, 6, 5, 4, 9}},
	}
	for _, c := range cases {
		got := ReaderOrder(c.seed, c.index, len(c.want))
		if !reflect.DeepEqual(got, c.want) {
			t.Errorf("ReaderOrder(%d, %d, %d)\n got %v\nwant %v (CPython)",
				c.seed, c.index, len(c.want), got, c.want)
		}
	}
}

// Whatever the permutation, it must be a permutation: every task exactly once.
// The conformance suite asserts this over HTTP; asserting it here as well means
// a regression names the generator rather than the endpoint.
func TestReaderOrderIsAPermutation(t *testing.T) {
	for _, n := range []int{0, 1, 2, 3, 6, 10, 101, 999} {
		for k := 0; k < 4; k++ {
			order := ReaderOrder(20260915, k, n)
			if len(order) != n {
				t.Fatalf("n=%d k=%d: got %d indices", n, k, len(order))
			}
			seen := make([]bool, n)
			for _, i := range order {
				if i < 0 || i >= n || seen[i] {
					t.Fatalf("n=%d k=%d: %v is not a permutation", n, k, order)
				}
				seen[i] = true
			}
		}
	}
}

// Two readers of the same batch must not be handed the same order — the reason
// the seed is offset by the reader's index at all.
func TestReadersGetDifferentOrders(t *testing.T) {
	a := ReaderOrder(4242, 0, 6)
	b := ReaderOrder(4242, 1, 6)
	if reflect.DeepEqual(a, b) {
		t.Fatalf("reader A and reader B were given the same order: %v", a)
	}
}
