#!/usr/bin/env bash
# Stop the dedicated stores for tenant 'sandbox'. Idempotent.
# Generated by apptainer/new-tenant.sh — do not edit; re-run it to regenerate.
set -euo pipefail
for name in qdrant-sandbox elasticsearch-sandbox; do
    if apptainer instance stop "$name" 2>/dev/null; then
        echo "[$name] stopped"
    else
        echo "[$name] not running"
    fi
done
