// Code generated by "go run ./internal/ctl/authz/gen"; DO NOT EDIT.
//
// Source: contracts/ctl/openapi.yaml, extension x-ctl-authorization-matrix.
// Regenerate after any contract change; matrix_test.go fails the build
// otherwise.

package authz

// Matrix is the deny-by-default authorization table: one row per contract
// operation, keyed by (METHOD, chi route pattern).
var Matrix = []Row{
	{OperationID: "ctlHealth", Method: "GET", Path: "/health", Role: "anonymous", Session: true, Mutating: false, ViewerFields: "all"},
	{OperationID: "ctlAudit", Method: "GET", Path: "/v1/audit", Role: "operator", Session: true, Mutating: false, ViewerFields: "n/a"},
	{OperationID: "ctlDoctor", Method: "GET", Path: "/v1/doctor", Role: "viewer", Session: true, Mutating: false, ViewerFields: "all; findings[].detail is path-redacted for a viewer"},
	{OperationID: "ctlFleet", Method: "GET", Path: "/v1/fleet", Role: "viewer", Session: true, Mutating: false, ViewerFields: "all"},
	{OperationID: "ctlGatewayStatus", Method: "GET", Path: "/v1/gateway", Role: "viewer", Session: true, Mutating: false, ViewerFields: "all"},
	{OperationID: "ctlGatewayApply", Method: "POST", Path: "/v1/gateway/apply", Role: "operator", Session: true, Mutating: true, ViewerFields: "n/a"},
	{OperationID: "ctlGatewayRender", Method: "POST", Path: "/v1/gateway/render", Role: "viewer", Session: true, Mutating: false, ViewerFields: "all"},
	{OperationID: "ctlJobsList", Method: "GET", Path: "/v1/jobs", Role: "viewer", Session: true, Mutating: false, ViewerFields: "jobs[] with worker, lock null; reservations, steps[].external_ids empty; steps[].log null"},
	{OperationID: "ctlJobShow", Method: "GET", Path: "/v1/jobs/{id}", Role: "viewer", Session: true, Mutating: false, ViewerFields: "as ctlJobsList"},
	{OperationID: "ctlJobCancel", Method: "POST", Path: "/v1/jobs/{id}/cancel", Role: "operator", Session: true, Mutating: true, ViewerFields: "n/a"},
	{OperationID: "ctlJobContinue", Method: "POST", Path: "/v1/jobs/{id}/continue", Role: "operator", Session: true, Mutating: true, ViewerFields: "n/a"},
	{OperationID: "ctlJobResume", Method: "POST", Path: "/v1/jobs/{id}/resume", Role: "operator", Session: true, Mutating: true, ViewerFields: "n/a"},
	{OperationID: "ctlJobSecrets", Method: "GET", Path: "/v1/jobs/{id}/secrets", Role: "operator", Session: false, Mutating: false, ViewerFields: "n/a"},
	{OperationID: "ctlJobStepLog", Method: "GET", Path: "/v1/jobs/{id}/steps/{n}/log", Role: "operator", Session: true, Mutating: false, ViewerFields: "n/a"},
	{OperationID: "ctlMe", Method: "GET", Path: "/v1/me", Role: "viewer", Session: true, Mutating: false, ViewerFields: "all"},
	{OperationID: "ctlSessionRevoke", Method: "DELETE", Path: "/v1/session", Role: "viewer", Session: true, Mutating: false, ViewerFields: "n/a"},
	{OperationID: "ctlSessionCreate", Method: "POST", Path: "/v1/session", Role: "viewer", Session: false, Mutating: false, ViewerFields: "all"},
	{OperationID: "ctlSettingsGet", Method: "GET", Path: "/v1/settings", Role: "viewer", Session: true, Mutating: false, ViewerFields: "all except recipients.fingerprints (empty for a viewer)"},
	{OperationID: "ctlSettingsPut", Method: "PUT", Path: "/v1/settings", Role: "operator", Session: true, Mutating: true, ViewerFields: "n/a"},
	{OperationID: "ctlTenantsList", Method: "GET", Path: "/v1/tenants", Role: "viewer", Session: true, Mutating: false, ViewerFields: "tenants[].{summary, status, units, drift}; tenants[].registry is null"},
	{OperationID: "ctlTenantCreate", Method: "POST", Path: "/v1/tenants", Role: "operator", Session: true, Mutating: true, ViewerFields: "n/a"},
	{OperationID: "ctlTenantShow", Method: "GET", Path: "/v1/tenants/{name}", Role: "viewer", Session: true, Mutating: false, ViewerFields: "summary, status, units, drift; registry is null"},
	{OperationID: "ctlTenantEnv", Method: "GET", Path: "/v1/tenants/{name}/env", Role: "viewer", Session: true, Mutating: false, ViewerFields: "keys[] with class == public only"},
	{OperationID: "ctlTenantLogs", Method: "GET", Path: "/v1/tenants/{name}/logs", Role: "operator", Session: true, Mutating: false, ViewerFields: "n/a"},
	{OperationID: "ctlTenantOp", Method: "POST", Path: "/v1/tenants/{name}/ops/{verb}", Role: "operator", Session: true, Mutating: true, ViewerFields: "n/a"},
	{OperationID: "ctlVersion", Method: "GET", Path: "/v1/version", Role: "viewer", Session: true, Mutating: false, ViewerFields: "all"},
}
