"""``X-Request-Id`` on every response, and the rules about the inbound header.

#427: a user's 503 could not be traced to its server log line because nothing
correlated the two. These pin the correlation id's four properties:

* it is **present** — on 2xx, on 404, on 422, and on the unhandled-500 path that
  Starlette generates above every middleware this app installs;
* it is **unique** per request, which is the property that makes it useful at all
  under concurrency;
* an inbound ``X-Request-ID`` is **never echoed** — ours is always ours;
* an inbound value that could forge a log line (a newline) or flood the log
  (200 characters) is **rejected outright** and never reaches a ``LogRecord``.
"""
import asyncio
import logging
import re

import pytest
from httpx import ASGITransport, AsyncClient

from ragstack.api.main import app
from ragstack.observability.context import RequestContextFilter
from ragstack.observability.middleware import _UPSTREAM_RE, RequestContextMiddleware

pytestmark = pytest.mark.asyncio

RID_RE = re.compile(r"^[0-9a-f]{16}$")


def _rid(response) -> str:
    value = response.headers.get("x-request-id")
    assert value is not None, f"no X-Request-Id on {response.status_code}"
    assert RID_RE.match(value), f"malformed request id {value!r}"
    return value


async def test_request_id_on_success(client):
    _rid(await client.get("/health"))


async def test_request_id_on_404_and_422(client):
    assert (await client.get("/v1/nope")).status_code == 404
    _rid(await client.get("/v1/nope"))
    # An empty body on a route that requires one is FastAPI's 422 — generated by
    # an exception handler, a different response path from a route's own return.
    r = await client.post("/v1/query", json={})
    assert r.status_code == 422, r.text
    _rid(r)


async def test_request_id_on_unhandled_500():
    """The A2 path: ``ServerErrorMiddleware`` is above every middleware
    ``add_middleware`` can install and renders its 500 with the ORIGINAL send, so
    the send-wrapper cannot stamp it. ``main._unhandled`` does, from the
    contextvar — and this test is what keeps that handler from being deleted as
    redundant.

    ``raise_app_exceptions=False`` because ``ServerErrorMiddleware`` re-raises
    after sending; without it httpx surfaces the exception instead of the
    response.
    """

    @app.get("/_test_boom")
    async def _boom() -> None:  # pragma: no cover - the raise is the point
        raise RuntimeError("kaboom")

    try:
        transport = ASGITransport(app=app, raise_app_exceptions=False)
        async with AsyncClient(transport=transport, base_url="http://test") as c:
            r = await c.get("/_test_boom")
        assert r.status_code == 500
        _rid(r)
    finally:
        app.router.routes = [
            r for r in app.router.routes if getattr(r, "path", None) != "/_test_boom"
        ]


async def test_two_requests_get_different_ids(client):
    first = _rid(await client.get("/health"))
    second = _rid(await client.get("/health"))
    assert first != second, "the same id on two requests defeats the entire mechanism"


async def test_inbound_request_id_is_not_echoed(client, caplog):
    """We always generate our own. A caller-supplied id is recorded as
    ``upstream_rid`` for gateway correlation and never becomes the response's.

    Captured at DEBUG because that is where OUR own per-request record is
    emitted. An earlier version used INFO and passed only by accident: the
    record it actually captured was httpx's own client line, which
    ``configure_logging`` now damps to WARNING. A test that depends on a third
    party's log level is a test that breaks for reasons unrelated to its subject.
    """
    caplog.set_level(logging.DEBUG)
    caplog.handler.addFilter(RequestContextFilter())

    inbound = "gateway-abc.123_XY"
    assert _UPSTREAM_RE.fullmatch(inbound)
    r = await client.get("/health", headers={"X-Request-ID": inbound})

    ours = _rid(r)
    assert ours != inbound
    upstreams = {getattr(rec, "upstream_rid", None) for rec in caplog.records}
    assert inbound in upstreams, "a valid inbound id should be recorded on the log record"


@pytest.mark.parametrize(
    "hostile",
    [
        "abc\ndef",  # log injection: a newline forges a whole second log line
        "abc\n",  # the TRAILING newline `$` matches before — hence fullmatch
        "a" * 64 + "\n",  # same hole, at the length boundary: 64 chars + LF
        "a" * 200,  # log flooding: an unbounded header on every line
        "a" * 65,  # one over the documented cap
        "id with spaces",  # breaks logfmt tokenisation
        "sub=1 rid=deadbeef",  # forges an adjacent logfmt field
        "",  # empty is not an id
    ],
)
async def test_hostile_inbound_id_is_rejected_and_never_logged(client, caplog, hostile):
    """The log-injection regression. A rejected inbound id must not merely be
    un-echoed — it must never reach a ``LogRecord`` at all, or the formatter
    writes the attacker's newline into the log file."""
    caplog.set_level(logging.DEBUG)
    caplog.handler.addFilter(RequestContextFilter())

    r = await client.get("/health", headers={"X-Request-ID": hostile})

    assert _rid(r) != hostile
    for rec in caplog.records:
        assert getattr(rec, "upstream_rid", "-") != hostile
        assert hostile not in rec.getMessage() if hostile else True


async def test_tenant_and_role_reach_the_log_record(client, caplog):
    """``resolve_principal`` puts the caller on the request context, and the
    filter carries it to every record. Removing that two-line write fails this.

    It does **not** pin mutate-versus-``set()``, and an earlier version of this
    docstring wrongly claimed it did: ``resolve_principal`` is an async
    dependency running in the request's own context chain, so a ``set()`` there
    is perfectly visible and converting it passes all 12 tests here. The
    distinction only bites inside an ``asyncio.gather`` child —
    ``tests/unit/test_request_context.py`` is where it is actually pinned.
    """
    caplog.set_level(logging.DEBUG)
    caplog.handler.addFilter(RequestContextFilter())

    r = await client.post("/v1/query", json={"query": "hello", "top_k": 1})
    assert r.status_code == 200, r.text

    tenants = {getattr(rec, "tenant", "-") for rec in caplog.records}
    assert tenants - {"-"}, "no log record carried a tenant"


async def test_request_id_is_readable_by_a_cross_origin_browser_client(client):
    """A browser can only read a response header the server explicitly exposes.
    Without ``expose_headers`` the frontend cannot see the id at all, which
    makes the "user reads it off the screen" half of #427 impossible.

    ``Retry-After`` is asserted alongside it because it has been documented on
    the 429/503 responses all along and has been unreadable cross-origin the
    entire time — a latent bug this fixes in passing, and one that would
    otherwise silently return the moment someone edits this list.
    """
    r = await client.get("/health", headers={"Origin": "https://example.test"})
    exposed = {
        h.strip().lower()
        for h in r.headers.get("access-control-expose-headers", "").split(",")
        if h.strip()
    }
    assert "x-request-id" in exposed, (
        "X-Request-Id is not in Access-Control-Expose-Headers — a cross-origin "
        "browser client cannot read it"
    )
    assert "retry-after" in exposed


@pytest.mark.parametrize(
    ("raised", "expected_outcome"),
    [
        (asyncio.CancelledError, "client_disconnected"),
        (RuntimeError, "unhandled"),
    ],
)
async def test_a_client_disconnect_is_not_recorded_as_a_server_error(
    caplog, raised, expected_outcome
):
    """``except BaseException`` also catches ``asyncio.CancelledError``, which on
    an ASGI server means the CLIENT went away — not a server fault.

    Harmless today because this line is DEBUG, but #427 W3 promotes it to
    INFO/WARNING with a status, at which point every user who closes a tab
    mid-query would manufacture a 500 in the log and, via W4's rollup, in the
    error rate. Pre-empted here so W3 inherits the right behaviour rather than
    having to notice it.

    Driven at the ASGI layer directly: httpx cannot produce a mid-request client
    disconnect against ``ASGITransport``, and the point is what the middleware
    records, not how the cancellation arrives.
    """
    caplog.set_level(logging.DEBUG)

    async def _app(scope, receive, send):
        raise raised()

    mw = RequestContextMiddleware(_app)
    scope = {"type": "http", "method": "GET", "path": "/v1/query", "headers": []}

    async def _send(message):  # pragma: no cover - never reached
        raise AssertionError("no response should be sent")

    with pytest.raises(raised):
        await mw(scope, None, _send)

    outcomes = [
        rec.outcome for rec in caplog.records if rec.name.endswith("observability.middleware")
    ]
    assert outcomes == [expected_outcome], f"recorded {outcomes}, expected {expected_outcome}"


async def test_a_lifespan_scope_gets_no_request_context(caplog):
    """A non-http scope must pass through without a context being installed.

    Not merely a short-circuit for speed: startup and shutdown run under the
    lifespan scope and log a great deal (the registry build, the ACL backfill,
    every "reranker enabled" line). Installing a request context there would
    stamp all of it with a request id that corresponds to no request — worse
    than no id, because ``grep rid=<that>`` would then return startup noise
    alongside a real request's lines.

    The assertion is on what a log record emitted during lifespan carries,
    because that is the thing an operator actually sees.
    """
    caplog.set_level(logging.DEBUG)
    caplog.handler.addFilter(RequestContextFilter())
    seen: list[str] = []

    async def _app(scope, receive, send):
        seen.append(scope["type"])
        logging.getLogger("ragstack.startup").info("registry built")

    mw = RequestContextMiddleware(_app)
    await mw({"type": "lifespan"}, None, None)

    assert seen == ["lifespan"], "the lifespan scope did not reach the app"
    startup = [r for r in caplog.records if r.name == "ragstack.startup"]
    assert startup, "the fake app's startup line was not captured"
    assert startup[0].rid == "-", (
        f"a startup log line carries rid={startup[0].rid!r} — a request id for no request"
    )
