"""``contracts/schemas/error.json`` — the repository's first error schema (#427 W6).

Three things are pinned here, and the first is the one conformance cannot do.

1. **The store-unavailable 503 body validates against the schema.** That body is
   the only one the contract wires ``content:`` to, and it is the body #427's
   incident produced. Triggering it black-box against a *healthy* server is not
   possible — you would have to break a store — so the deterministic pin lives
   here, where ``app.state.retriever`` can be swapped for one that raises.
   ``conformance/test_error_shape.py`` covers what a black-box test genuinely
   can: the error bodies a healthy server always produces.

2. **The two copies of the schema agree.** The repo maintains
   ``contracts/schemas/*.json`` (what conformance validates against) and
   ``openapi.yaml``'s ``components.schemas`` (what the published document says)
   in parallel, by hand. ``test_admin_log_level.py`` set the precedent for
   asserting they have not drifted; this does the same for ``Error``.

3. **``detail`` stays untyped.** It is a string almost everywhere, an array for
   FastAPI's 422 and an object for the ``owner_quota_exceeded`` 409. The
   temptation to "tidy" it to ``{"type": "string"}`` would make the schema wrong
   for two shapes that already ship, and nothing else would catch it — the 409
   is not on the query path and the 422 body is generated by FastAPI. So both
   shapes are asserted against the schema directly.
"""
from __future__ import annotations

import json
from pathlib import Path

import jsonschema
import pytest
import yaml

from ragstack.api.main import app
from ragstack.stores.errors import KIND_TIMEOUT, STORE_FAILURE_KINDS, StoreUnavailable

_CONTRACTS = Path(__file__).resolve().parents[3] / "contracts"
ERROR_SCHEMA = json.loads((_CONTRACTS / "schemas" / "error.json").read_text())


class _UnavailableRetriever:
    async def retrieve(self, *args: object, **kwargs: object) -> object:
        raise StoreUnavailable(
            "qdrant",
            "qdrant search on 'ragstack_lib_open_access' at http://store:6333 failed "
            "— ReadTimeout: timed out; per-request timeout is 30s (QDRANT_TIMEOUT)",
            kind=KIND_TIMEOUT,
            elapsed_s=30.4,
        )


async def _query_with_retriever(client, retriever):
    saved = app.state.retriever
    app.state.retriever = retriever
    try:
        return await client.post("/v1/query", json={"query": "what is RAG?"})
    finally:
        app.state.retriever = saved


# --------------------------------------------------------------------------- #
# 1. The body the contract wires the schema to
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("endpoint", ["/v1/query", "/v1/retrieve"])
@pytest.mark.asyncio
async def test_the_store_unavailable_503_validates_against_error_json(client, endpoint):
    """The deterministic pin: the exact body ``content:`` promises.

    Both endpoints, because the contract wires the schema to both and they take
    different code paths through the router to the same exception handler.
    """
    saved = app.state.retriever
    app.state.retriever = _UnavailableRetriever()
    try:
        resp = await client.post(endpoint, json={"query": "what is RAG?"})
    finally:
        app.state.retriever = saved

    assert resp.status_code == 503, resp.text
    body = resp.json()
    jsonschema.validate(instance=body, schema=ERROR_SCHEMA)

    # Validating a body that happened to be missing the interesting fields would
    # pass vacuously — assert they are actually there and actually constrained.
    assert body["reason"] in STORE_FAILURE_KINDS
    assert body["request_id"] == resp.headers["x-request-id"]


@pytest.mark.asyncio
async def test_the_schema_would_reject_an_unmodelled_key(client):
    """``additionalProperties: false`` is the whole reason D4 kept ``store`` out
    of the schema. If it were not enforced, the test above would pass no matter
    what the handler added to the body, and the decision would be moot."""
    resp = await _query_with_retriever(client, _UnavailableRetriever())
    body = dict(resp.json())
    body["store"] = "qdrant"
    with pytest.raises(jsonschema.ValidationError):
        jsonschema.validate(instance=body, schema=ERROR_SCHEMA)


# --------------------------------------------------------------------------- #
# 2. The two copies of the schema agree
# --------------------------------------------------------------------------- #


def test_openapi_error_component_matches_error_json():
    openapi = yaml.safe_load((_CONTRACTS / "openapi.yaml").read_text())
    component = openapi["components"]["schemas"]["Error"]

    assert component["required"] == ERROR_SCHEMA["required"] == ["detail"]
    assert component["additionalProperties"] is False
    assert ERROR_SCHEMA["additionalProperties"] is False
    assert set(component["properties"]) == set(ERROR_SCHEMA["properties"])
    assert (
        component["properties"]["reason"]["enum"]
        == ERROR_SCHEMA["properties"]["reason"]["enum"]
        == list(STORE_FAILURE_KINDS)
    )
    assert (
        component["properties"]["request_id"]["pattern"]
        == ERROR_SCHEMA["properties"]["request_id"]["pattern"]
    )
    # `detail` carries no `type` in either copy — see the module docstring.
    assert "type" not in component["properties"]["detail"]
    assert "type" not in ERROR_SCHEMA["properties"]["detail"]


def test_the_schema_is_wired_to_both_503s_and_names_the_store_cause():
    """The contract's 503 prose listed authz / dormant / restoring / at-capacity
    and never mentioned a store failure — the incident's own failure mode was
    absent from the document that describes the endpoint it happened on."""
    openapi = yaml.safe_load((_CONTRACTS / "openapi.yaml").read_text())
    for path in ("/v1/query", "/v1/retrieve"):
        resp = openapi["paths"][path]["post"]["responses"]["503"]
        assert resp["content"]["application/json"]["schema"] == {
            "$ref": "#/components/schemas/Error"
        }
        description = resp["description"]
        assert "backing store did not answer" in description
        for kind in STORE_FAILURE_KINDS:
            assert f"reason: {kind}" in description


# --------------------------------------------------------------------------- #
# 3. `detail` stays untyped
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    "detail",
    [
        pytest.param("qdrant unavailable: search timed out", id="string"),
        pytest.param(
            [{"loc": ["body", "query"], "msg": "field required", "type": "missing"}],
            id="array-fastapi-422",
        ),
        pytest.param(
            {"error": "owner_quota_exceeded", "owned": 5, "limit": 5, "message": "…"},
            id="object-owner-quota-409",
        ),
    ],
)
def test_detail_accepts_every_shape_the_api_already_emits(detail):
    jsonschema.validate(instance={"detail": detail}, schema=ERROR_SCHEMA)


@pytest.mark.asyncio
async def test_a_real_422_body_validates(client):
    """FastAPI generates this one; nothing in this repo shapes it. If the schema
    ever tightened `detail` to a string, this is the body that would break."""
    resp = await client.post("/v1/query", json={"not_a_query": 1})
    assert resp.status_code == 422, resp.text
    assert isinstance(resp.json()["detail"], list)
    jsonschema.validate(instance=resp.json(), schema=ERROR_SCHEMA)


@pytest.mark.asyncio
async def test_a_real_404_body_validates(client):
    """The other 503-adjacent error on the same endpoint: an unknown collection.
    A `detail`-only body with no `reason` and no `request_id` — which is why
    both are optional rather than required."""
    resp = await client.post(
        "/v1/query", json={"query": "x", "collection": "no_such_collection"}
    )
    assert resp.status_code == 404, resp.text
    body = resp.json()
    assert set(body) == {"detail"}
    jsonschema.validate(instance=body, schema=ERROR_SCHEMA)
