"""``X-Request-Id`` on every response, and the rules about the inbound header.

#427: a user's 503 could not be traced to its server log line because nothing
correlated the two. These pin the correlation id's four properties:

* it is **present** — on 2xx, on 404, on 422, and on the unhandled-500 path that
  Starlette generates above every middleware this app installs;
* it is **unique** per request, which is the property that makes it useful at all
  under concurrency;
* an inbound ``X-Request-ID`` is **never echoed** — ours is always ours;
* an inbound value that could forge a log line (a newline) or flood the log
  (200 characters) is **rejected outright** and never reaches a ``LogRecord``.
"""
import logging
import re

import pytest
from httpx import ASGITransport, AsyncClient

from ragstack.api.main import app
from ragstack.observability.context import RequestContextFilter
from ragstack.observability.middleware import _UPSTREAM_RE

pytestmark = pytest.mark.asyncio

RID_RE = re.compile(r"^[0-9a-f]{16}$")


def _rid(response) -> str:
    value = response.headers.get("x-request-id")
    assert value is not None, f"no X-Request-Id on {response.status_code}"
    assert RID_RE.match(value), f"malformed request id {value!r}"
    return value


async def test_request_id_on_success(client):
    _rid(await client.get("/health"))


async def test_request_id_on_404_and_422(client):
    assert (await client.get("/v1/nope")).status_code == 404
    _rid(await client.get("/v1/nope"))
    # An empty body on a route that requires one is FastAPI's 422 — generated by
    # an exception handler, a different response path from a route's own return.
    r = await client.post("/v1/query", json={})
    assert r.status_code == 422, r.text
    _rid(r)


async def test_request_id_on_unhandled_500():
    """The A2 path: ``ServerErrorMiddleware`` is above every middleware
    ``add_middleware`` can install and renders its 500 with the ORIGINAL send, so
    the send-wrapper cannot stamp it. ``main._unhandled`` does, from the
    contextvar — and this test is what keeps that handler from being deleted as
    redundant.

    ``raise_app_exceptions=False`` because ``ServerErrorMiddleware`` re-raises
    after sending; without it httpx surfaces the exception instead of the
    response.
    """

    @app.get("/_test_boom")
    async def _boom() -> None:  # pragma: no cover - the raise is the point
        raise RuntimeError("kaboom")

    try:
        transport = ASGITransport(app=app, raise_app_exceptions=False)
        async with AsyncClient(transport=transport, base_url="http://test") as c:
            r = await c.get("/_test_boom")
        assert r.status_code == 500
        _rid(r)
    finally:
        app.router.routes = [
            r for r in app.router.routes if getattr(r, "path", None) != "/_test_boom"
        ]


async def test_two_requests_get_different_ids(client):
    first = _rid(await client.get("/health"))
    second = _rid(await client.get("/health"))
    assert first != second, "the same id on two requests defeats the entire mechanism"


async def test_inbound_request_id_is_not_echoed(client, caplog):
    """We always generate our own. A caller-supplied id is recorded as
    ``upstream_rid`` for gateway correlation and never becomes the response's."""
    caplog.set_level(logging.INFO)
    caplog.handler.addFilter(RequestContextFilter())

    inbound = "gateway-abc.123_XY"
    assert _UPSTREAM_RE.match(inbound)
    r = await client.get("/health", headers={"X-Request-ID": inbound})

    ours = _rid(r)
    assert ours != inbound
    upstreams = {getattr(rec, "upstream_rid", None) for rec in caplog.records}
    assert inbound in upstreams, "a valid inbound id should be recorded on the log record"


@pytest.mark.parametrize(
    "hostile",
    [
        "abc\ndef",  # log injection: a newline forges a whole second log line
        "a" * 200,  # log flooding: an unbounded header on every line
        "id with spaces",  # breaks logfmt tokenisation
        "sub=1 rid=deadbeef",  # forges an adjacent logfmt field
        "",  # empty is not an id
    ],
)
async def test_hostile_inbound_id_is_rejected_and_never_logged(client, caplog, hostile):
    """The log-injection regression. A rejected inbound id must not merely be
    un-echoed — it must never reach a ``LogRecord`` at all, or the formatter
    writes the attacker's newline into the log file."""
    caplog.set_level(logging.DEBUG)
    caplog.handler.addFilter(RequestContextFilter())

    r = await client.get("/health", headers={"X-Request-ID": hostile})

    assert _rid(r) != hostile
    for rec in caplog.records:
        assert getattr(rec, "upstream_rid", "-") != hostile
        assert hostile not in rec.getMessage() if hostile else True


async def test_tenant_and_role_reach_the_log_record(client, caplog):
    """``resolve_principal`` mutates the shared context object IN PLACE rather
    than re-``set()``ing the contextvar. If someone converts that to a ``set()``
    the value silently stops reaching the record and this fails."""
    caplog.set_level(logging.DEBUG)
    caplog.handler.addFilter(RequestContextFilter())

    r = await client.post("/v1/query", json={"query": "hello", "top_k": 1})
    assert r.status_code == 200, r.text

    tenants = {getattr(rec, "tenant", "-") for rec in caplog.records}
    assert tenants - {"-"}, "no log record carried a tenant"
