// Named aliases over the generated control-plane contract types
// (`ctlSchema.d.ts`, regenerated by `npm run gen:ctl-api`). Nothing here
// invents a shape: every alias resolves to something in
// `contracts/ctl/schemas/*.json`, so a contract change that the UI ignores is a
// type error rather than a runtime surprise.
//
// The one transformation is `Body<T>`: the JSON-Schema files carry their own
// `$defs`, openapi-typescript keeps that member on the emitted object type, and
// a response body never contains it. Stripping it here is what lets a fixture
// (and a real response) satisfy the type.

import type { components } from "./ctlSchema";

type S = components["schemas"];

/** A response body as it actually arrives: the schema minus its own `$defs`. */
type Body<T> = Omit<T, "$defs">;

export type CtlVersion = Body<S["version_response"]>;
export type CtlMe = Body<S["me_response"]>;
export type CtlSessionResponse = Body<S["session_response"]>;

export type CtlFleet = Body<S["fleet_response"]>;
export type FleetRow = S["FleetRow"];
export type FleetHost = S["Host"];
export type HealthState = S["HealthState"];
export type UnitState = S["UnitState"];

export type CtlTenant = Body<S["tenant_response"]>;
export type LiveStatus = S["LiveStatus"];
export type TenantUnits = S["Units"];
export type DriftRow = S["DriftRow"];

export type CtlEnv = Body<S["env_response"]>;
export type EnvKey = S["EnvKey"];

export type CtlLogs = Body<S["logs_response"]>;
export type LogFile = CtlLogs["file"];

export type CtlDoctor = Body<S["doctor_response"]>;
export type DoctorFinding = S["Finding"];

export type CtlGateway = Body<S["gateway_status"]>;
export type GatewayRoute = S["Route"];
export type CtlGatewayRender = Body<S["gateway_render_response"]>;

export type CtlErrorBody = Body<S["error"]>;
export type CtlErrorCode = CtlErrorBody["code"];

/** `viewer` sees the summary allowlist; `operator` sees everything. */
export type CtlRole = CtlMe["role"];
