// Named aliases over the generated control-plane contract types
// (`ctlSchema.d.ts`, regenerated by `npm run gen:ctl-api`). Nothing here
// invents a shape: every alias resolves to something in
// `contracts/ctl/schemas/*.json`, so a contract change that the UI ignores is a
// type error rather than a runtime surprise.
//
// The one transformation is `Body<T>`: the JSON-Schema files carry their own
// `$defs`, openapi-typescript keeps that member on the emitted object type, and
// a response body never contains it. Stripping it here is what lets a fixture
// (and a real response) satisfy the type.

import type { components } from "./ctlSchema";
type S = components["schemas"];

/** A response body as it actually arrives: the schema minus its own `$defs`. */
type Body<T> = Omit<T, "$defs">;

export type CtlVersion = Body<S["version_response"]>;
export type CtlMe = Body<S["me_response"]>;
export type CtlSessionResponse = Body<S["session_response"]>;

export type CtlFleet = Body<S["fleet_response"]>;
export type FleetRow = S["FleetRow"];
export type FleetHost = S["Host"];
export type HealthState = S["HealthState"];
export type UnitState = S["UnitState"];

export type CtlTenant = Body<S["tenant_response"]>;
export type LiveStatus = S["LiveStatus"];
export type TenantUnits = S["Units"];
export type DriftRow = S["DriftRow"];

export type CtlEnv = Body<S["env_response"]>;
export type EnvKey = S["EnvKey"];

export type CtlLogs = Body<S["logs_response"]>;
export type LogFile = CtlLogs["file"];

export type CtlDoctor = Body<S["doctor_response"]>;
export type DoctorFinding = S["Finding"];

export type CtlGateway = Body<S["gateway_status"]>;
export type GatewayRoute = S["Route"];
export type CtlGatewayRender = Body<S["gateway_render_response"]>;

export type CtlErrorBody = Body<S["error"]>;
export type CtlErrorCode = CtlErrorBody["code"];

/** `viewer` sees the summary allowlist; `operator` sees everything. */
export type CtlRole = CtlMe["role"];

// ---------------------------------------------------------------------------
// Mutations (PR-G): the envelope, what a dry run answers, what an execute
// answers, and the reads that follow a job.
// ---------------------------------------------------------------------------

/** A dry run's 200 body: what the op WOULD do. */
export type Plan = Body<S["plan"]>;
export type PlannedStep = S["PlannedStep"];

/** An execute's 202 body, and `GET /v1/jobs/{id}`. */
export type Job = Body<S["job"]>;
export type Step = S["Step"];
export type JobState = S["JobState"];

/**
 * The mutation envelope. `args` is generated as `Record<string, never>` (the
 * schema says only `type: object`; the per-verb shapes live in
 * `x-ctl-op-args`, which openapi-typescript does not see), so ops.ts builds it
 * from a plain object rather than through this alias.
 */
export type OpRequest = S["op_request"];
/** Every verb the job engine knows, including `create` and `adopt`. */
export type OpVerb = S["OpVerb"];
/**
 * The verbs `POST /v1/tenants/{name}/ops/{verb}` accepts — the path
 * parameter's own enum, narrower than `OpVerb` (no `create`, no `adopt`).
 */
export type TenantOpVerb = components["parameters"]["Verb"];
export type CreateArgs = S["CreateArgs"];

export type JobsResponse = Body<S["jobs_response"]>;
export type AuditResponse = Body<S["audit_response"]>;
export type AuditRow = S["AuditRow"];
/** The ONLY body in this API that carries a secret value. Never cache it. */
export type SecretsResponse = Body<S["secrets_response"]>;
export type SettingsResponse = Body<S["settings_response"]>;
export type ArtifactsResponse = Body<S["artifacts_response"]>;
export type ArtifactRow = ArtifactsResponse["artifacts"][number];

export type KeyRecord = S["KeyRecord"];
export type ServiceAccountRecord = S["ServiceAccountRecord"];
